<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Faculty registration codes: generated by the Admin, shared with faculty
 * staff, and required on the Faculty Register page. A code is single-use;
 * once a faculty account registers with it, used_by/used_at are stamped
 * (shown RED on the admin page, unused codes show GREEN).
 */
return new class extends Migration
{
    public function up(): void
    {
        if (! Schema::hasTable('faculty_codes')) {
            Schema::create('faculty_codes', function (Blueprint $table) {
                $table->id();
                $table->string('code', 20)->unique();
                $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
                $table->foreignId('used_by')->nullable()->constrained('users')->nullOnDelete();
                $table->timestamp('used_at')->nullable();
                $table->timestamps();
            });
        }
    }

    public function down(): void
    {
        Schema::dropIfExists('faculty_codes');
    }
};
